* Γενικά
  Η προσομοίωση αποτελείται από δύο βασικά στοιχεία, την ακτογραμμή (terrain) και το
  ρευστό (fluid). Το ρευστό είναι το δυναμικό στοιχείο, σε αντίθεση με την ακτογραμμή που
  είναι στατική. Στο πρόγραμμα προσομοίωσης, που στηρίζεται στη μηχανή φυσικής Bullet,
  δίνονται οι αρχικές συνθήκες του ρευστού (θέση και ταχύτητα) και εισάγεται η ακτογραμμή
  με τη μορφή 3Δ τριγωνικού πλέγματος επιφάνειας (mesh). Στη συνέχεια η προσομοίωση
  γίνεται offline και τα δεδομένα εξάγονται σε αρχεία τύπου vtk που μπορούν εισαχθούν σε
  ένα από τα πολλά προγράμματα οπτικοποίησης που είναι διαθέσιμα ελεύθερα (πχ Paraview).

* Ακτογραμμή
** Αρχικοποίηση και αναπαράσταση
   Η ακτογραμμή αναπαρίσταται στο πρόγραμμα σαν ένα πλέγμα τριγώνων με ιεραρχικούς
   περιβάλλοντες όγκους (bounding volume hierarchy triangle mesh -- btBvhTriangleMesh) της
   Bullet. Τα δεδομένα του 3Δ μοντέλου εισάγονται από ένα αρχείο obj στο τριγωνικό πλέγμα
   αφού κανονικοποιηθούν σε κλίμακα βάσει ενός παράγοντα κλιμάκωσης (scaling factor) και
   θέση μετακινούμενα στο χώρο προς την αρχή των αξόνων (docking). Γύρω από την ακτογραμμή
   δημιουργείται και το όριό της (terrain boundary) το οποίο ταυτίζεται με το
   προσανατολισμένο στους άξονες περιβάλλον κουτί της (AABB). Η κανονικοποιημένη
   ακτογραμμή και το όριό της εξάγονται σε ένα αρχείο vtk, το οποίο χρησιμοποιείται για
   την οπτικοποίηση των δεδομένων.

** Ώσεις
   Σε κάθε εσωτερικό βήμα της προσομοίωσης συλλέγονται οι ώσεις που ασκεί το ρευστό στην
   ακτογραμμή σε ειδικό διάνυσμα, το οποίο χρησιμοποιείται για να εξαχθούν οι σχετικές
   πληροφορίες σε κάθε στιγμιότυπο.

* Ρευστό
** SPH (Smoothed Particle Hydrodynamics)
   Η SPH στηρίζεται στη διακριτοποίηση του ρευστού σε σωματίδια, τα οποία όμως δεν είναι
   παρά σημεία δειγματοληψίας και παρεμβολής για τον υπολογισμό των ιδιοτήτων του ρευστού
   σε οποιοδήποτε σημείο του χώρου. Η μέθοδος αναπτύχθηκε για την προσομοίωση αστροφυσικών
   φαινομένων, όπως τη δημιουργία γαλαξιών, τη συμπεριφορά αστρικών νεφών κα. Στη μέθοδο
   αυτή, οι ιδιότητες του ρευστού σε οποιοδήποτε σημείο υπολογίζονται ως σταθμισμένο
   άθροισμα των αντίστοιχων ιδιοτήτων των γειτονικών σωματιδίων, οι συντελεστές του οποίου
   εξάγονται από έναν πυρήνα εξομάλυνσης (smoothing kernel), συναρτήσει της απόστασης κάθε
   γείτονα. Αυτή η μέθοδος παρεμβολής ενδείκνυται για συμπιεστά ρευστά (αέρια), λόγω των
   σημαντικών αποκλίσεων που μπορούν να προκύψουν εξαιτίας της έλλειψης γειτόνων. Σε
   ασυμπίεστα ρευστά (υγρά), αυτό οδηγεί σε εσφαλμένες εκτιμήσεις της πυκνότητας σε
   περιοχές κοντά στην επιφάνεια του ρευστού, σε σταγονίδια (droplets), κλπ. Για το λόγο
   αυτό στην παρούσα εφαρμογή τα σωματίδια έχουν και υλική υπόσταση (στερεές σφαίρες)
   προκειμένου να διασφαλιστεί η ασυμπιεστότητα (incompressiblity) και να αποφευχθεί η
   συσσώρευση (stacking), ακόμα και ανάμεσα σε απομονωμένα ζεύγη σωματιδίων.

** Αρχικοποίηση
   Για την αρχικοποίηση του ρευστού δίνεται η θέση του στο χώρο, η αρχική ταχύτητα και το
   επιθυμητό πλήθος των σωματιδίων στα οποία πρόκειται να διακριτοποιηθεί. Τα σωματίδια
   έχουν σφαιρικό σχήμα και τοποθετούνται σε 3Δ εξαγωνικό πλέγμα HCP (Hexagonal
   Close-Packed), το οποίο επιτυγχάνει τη συνεκτικότερη δυνατή διευθέτηση ίσομεγεθών
   σφαιρών με κλάσμα κάλυψης χώρου ίσο με π/(3*sqrt(2)). Κατά το στάδιο αυτό ορίζεται και
   η ακτίνα εξομάλυνσης (smoothing radius) τέτοια ώστε κάθε σωματίδιο να έχει περίπου 50
   γειτονικά σωματίδια με τα οποία αλληλεπιδρά.

** Παράμετροι
   Μετά την αρχικοποίηση εξάγονται παράμετροι της εξομοίωης που έχουν να κάνουν σχετικά με
   το ρευστό και την ακτογραμμή:
   - *Χρονικό βήμα* Το χρονικό βήμα καθορίζεται από το κριτήριο ευστάθειας CFL
     (Courant-Friedrichs-Lewy): dt = C * dx/v_max, όπου C είναι ο αδιάστατος αριθμός
     Courant (συνήθως 0 < C < 1), dx είναι το χαρακτηριστικό μήκος (επιλέγεται η ακτίνα
     των σωματιδίων) και v_max η μέγιστη ταχύτητα ενός σωματιδίου. Η v_max εκτιμάται από
     τη μέγιστη μηχανική ενέργεια των σωματιδίων στις αρχικές συνθήκες.
   - *Πλήθος γειτόνων* Στην αρχική κατάσταση όπου τα σωματίδια είναι διευθετημένα στο
     πλέγμα HCP, γίνεται ανίχνευση γειτόνων ώστε να μετρηθεί ο πραγματικός μέγιστος
     αριθμός γειτόνων ένός σωματιδίου (ο οποίος δεν είναι σχεδόν ποτέ ακριβώς 50 λόγω
     διακριτοποίησης).
   - *Συντελεστής πυκνότητας* Λόγω της εξάρτησης των πυρήνων εξομάλυνσης από την ακτίνα
     εξομάλυνσης, αλλά και της μάζας των σωματιδίων από τη διακριτοποίηση, το άθροισμα της
     πυκνότητας δεν ισούται με την πυκνότητα του ρευστού, αλλά σχετίζεται αναλογικά με
     έναν συντελεστή, ο οποίος εξάγεται κατά το στάδιο αυτό και χρησιμοποιείται για την
     αναλογική αντιστοίχιση της αδιάστατης πυκνότητας με την πραγματική. Ο συντελεστής
     υπολογίζεται με βάση τη μέγιστη πυκνότητα των σωματιδίων κατά την ανίχνευση γειτόνων
     στην αρχική κατάσταση που αναφέρεται παραπάνω.

** Αναπαράσταση
   Το ρευστό διακριτοποιείται σε υλικά σωματίδια, το πλήθος των οποίων εξαρτάται από την
   επιθυμητή αναλυτικότητα (resolution) της προσομοίωσης. Η μάζα του ρευστού
   ισοκατανέμεται στα σωματίδια, τα οποία λειτουργούν και σαν σημεία δειγματοληψίας και
   ελέγχου και για άλλες ιδιότητές του σύμφωνα με τη μέθοδο SPH. Μ' αυτόν τον τρόπο, τα
   σωματίδια εμπλουτίζουν/περικλείουν (wrappers) τα αντικείμενα στερεών σωμάτων
   (btRigidBody) της bullet, με πληροφορίες που σχετίζονται με ιδιότητες του ρευστού
   (πυκνότητα, πίεση, ιξώδες, κα).

*** LP grid
    Για την καλύτερη απόδοση του προγράμματος προσομοίωσης αναπτύχθηκε εξειδικευμένη δομή
    δεδομένων με σκοπό τη γρήγορη πρόσβαση στα σωματίδια. Ο χώρος διαιρείται σε ένα κυβικό
    πλέγμα προσανατολισμένο με το τρισορθογώνιο σύστημα συντεταγμένων, με το βήμα του
    πλέγματος (μήκος πλευράς των κύβων) να ισούται με την ακτίνα εξομάλυνσης της
    προσομοίωσης. Με τον τρόπο αυτό όλοι οι γείτονες ενός σωματιδίου βρίσκονται στα 26
    κελιά που περιβάλλουν το κελι στο οποίο ανήκει. Η διάταξη των κελιών στη μνήμη έχει
    στόχο την διατήρηση της τοπικότητας (locality preserving), ώστε κελιά που βρίσκονται
    κοντά στον 3Δ χώρο να βρίσκονται κοντά και στη μνήμη (η οποία είναι γραμμική -- 1Δ),
    προκειμένου να βελτιστοποιηθεί η χρήση της κρυφής μνήμης (cache).

**** Οργάνωση
     H δομή (LP grid) αποτελείται κυρίως από 3 διανύσματα:
     - *MAP* Στο διάνυσμα αυτό αποθηκεύονται δείκτες προς το διάνυσμα anchors. Σκοπός του
       map είναι διευθυνσιοδότηση σύμφωνα με τη βέλτιστη για την διατήρηση της τοπικότητας
       διάταξη (3Δ σε 1Δ) των κελιών. Διαθέτει (#κελιά)+1 στοιχεία, με το επιπλέον
       στοιχείο να αντιστοιχεί σε ένα εικονικό κελί που περιέχει σωματίδια εκτός ορίων του
       πλέγματος.
     - *ANCHORS* Κάθε δείκτης του διανύσματος anchors σηματοδοτεί την αρχή του εκάστοτε
       κελιού (το πρώτο σωματίδιο) στο διάνυσμα particles. Τα σωματίδια κάθε κελιού
       βρίσκονται συνεχόμενα στο διάνυσμα particles, ενώ τα κελιά αντιπροσωπεύονται
       διατεταγμένα προς διατήρηση τοπικότητας στο anchors. Συνεπώς για τα στοιχεία του
       τελευταίου ισχύει A[i-1] <= A[i] (οταν A[i-1] = A[i], το κελί που αντιστοιχεί στο
       A[i-1] δεν περιέχει κανένα σωματίδιο). Το διάνυσμα διαθέτει και αυτό (#κελιά)+1
       στοιχεία.
     - *PARTICLES* Σ' αυτό το διάνυσμα αποθηκεύονται δείκτες προς τα σωματίδια της
       προσομοίωσης και διαθέτει (#σωματίδια)+1 θέσεις. Η επιπλέον θέση χρησιμοποιείται
       για έγκυρο δείκτη τέλους του τελευταίου (εικονικού) κελιού (τα σωματίδια του οποίου
       αποθηκεύονται στις τελευταίες θέσεις του particles), καθώς και για έγκυρη
       αρχικοποίηση (κατά τη διάρκεια της οποίας υπάρχει δείκτης που δείχνει στη θέση
       αυτή).
     Στη δομή αποθηκεύονται και άλλα στοιχεία που αφορούν το πλέγμα: η αρχή του (origin),
     το βήμα του (step), το πλήθος των κελιών κατά μήκος κάθε άξονα (x, y, z) και το
     πλήθος κελιών και σωματιδίων (cell_count, paritlce_count).

**** Πρόσβαση
     Η πρόσβαση στα κελιά του πλέγματος γίνεται με καθοδήγηση μέσω δεικτών (pointer
     cascading). Ένα κελί είναι ένα ζεύγος δεικτών στο διάνυσμα particles, με τον πρώτο να
     δείχνει στο πρώτο του σωματίδιο και το δευτερο στο πρώτο σωματίδιο του επόμενου
     κελιού. Έστω οτι ζητούνται τα περιεχόμενα του κελιού στη διεύθυνση (i, j, k) του
     πλέγματος. Η 3Δ διεύθυνση μετατρέπεται σε 1Δ (έναν αριθμητικό δείκτη) μέσω μιας
     συνάρτησης linearize. Η συνάρτηση αυτή πρέπει να δίνει διαφορετικό αποτέλεσμα για
     κάθε έγκυρη 3Δ διεύθυνση εισόδου και πεδίο τιμών στο [0, (#κελιά)+1], προκειμένου η
     έξοδος να αποτελεί διεύθυνση για το διάνυσμα map. Τότε η αρχή του κελίου είναι ο
     δείκτης map[linearize(i, j, k)] και το τέλος map[linearize(i, j, k)]+1, με αποτέλεσμα
     τα σωματίδια του κελιού να βρίσκονται με έναν απλό βρόχο επανάληψης ανάμεσα στους δύο
     δείκτες, συμπεριλαμβανομένου του αρχικού, αλλά όχι του τελικού (δείκτης στο πρώτο
     σωματίδιο του επόμενου κελιού).

**** Αρχικοποίηση
     Για την δημιουργία του πλέγματος ακολουθούνται τα παρακάτω βήματα:
     1. Καθορίζεται η αρχή του πλέγματος, το βήμα, το πλήθος κελιών και σωματιδίων του και
        δεσμεύεται βάσει αυτών χώρος στη μνήμη.
     2. Τα κελιά του πλέγματος ταξινομούνται στο χώρο (spatial sort) κατά μήκος μιας
        καμπύλης πλήρωσης χώρου (space-filling curve), ώστε στην τελική γραμμική διάταξη
        να διατηρείται η τοπικότητα κατά το μέγιστο δυνατό. Στη συνέχεια αρχικοποιείται το
        διάνυσμα map, ώστε στη θέση map[linearize(i, j, k)] να υπάρχει δείκτης στην
        αντίστοιχη θέση του anchors σύμφωνα με τη χωρική ταξινόμηση των κελιών.
     3. Κατασκευάζεται ένα διάνυσμα σε κάθε θέση του οποίου αποθηκεύεται ο αριθμός των
        σωματιδίων σε κάθε κελί (προφανώς απαιτείται ανάγνωση των σωματιδίων), και σύμφωνα
        με αυτό αρχικοποιούνται οι δείκτες στο διάνυσμα anchors.
     4. Τα σωματίδια αποθηκεύονται στο διάνυσμα particles, στη θέση που δείχνουν οι
        anchors, ενώ μετά την προσθήκη κάθε σωματιδίου, ο εκάστοτε anchor αυξάνεται κατά 1
        (δείχνει στην επόμενη θέση του particles). Στο τέλος της διαδικασίας αυτής κάθε
        anchor δείχνει στην αρχή του επόμενου κελιού (και ο τελευταίος στην τελευταία
        επιπλέον θέση του particles). Οι anchors επαναφέρονται στις κανονικές τους θέσεις
        (ο καθένας εκεί που δείχνει ο προηγούμενος και ο πρώτος στην αρχή του particles)
        και το διάνυσμα πλήθους σωματιδίων ανά κελί διαγράφεται.
	
**** Ενημέρωση
     Μετά από κάθε βήμα της προσομοίωσης τα σωματίδια έχοντας μετακινηθεί ενδέχεται να
     βρίσκονται σε διαφορετικό κελί του πλέγματος, το οποίο πρέπει να ενημερωθεί. Τα
     σωματίδια ελέγχονται με τη σειρά και σε περίπτωση σφάλματος, γίνεται κυκλική
     μετακίνηση κατά μία θέση (shift) δεξιά/αριστερά στο τμήμα του διανύσματος particles
     μεταξύ της τρέχουσας και ορθής θέσης του σωματιδίου και αντίστοιχη μετακίνηση (+/- 1)
     των anchors του τμήματος αυτού. Στη χειρότερη περίπτωση η διαδικασία αυτή έχει
     απαγορευτική ασυμπτωτική συμπεριφορά (Ο(n^2)) σε συνήθεις όμως περιπτώσεις απαιτεί
     πολύ λιγότερο χρόνο, διότι:
     1. Κατά κανόνα μικρό πλήθος σωματιδίων αλλάζουν κελί σε κάθε βήμα, δεδομένου οτι τα
        κελιά είναι αρκετά μεγάλα σε σχέση με το μέγεθος και την ταχύτητα των σωματιδίων.
     2. Η διατήρηση της τοπικότητας εξασφαλίζει οτι τα κελιά άφιξης και προορισμού του
        σωματιδίου (τα οποία αναμένεται να είναι γειτονικά σε λογικό χρονικό βήμα)
        βρίσκονται κοντά στη γραμμική αναπαράσταση, με αποτέλεσμα η διαδικασία ενημέρωσης
        να αφορά μικρό τμήμα των διανυσμάτων particles και anchors.
    
*** Ανίχνευση αλληλεπιδράσεων
    Για τον υπολογισμό των ιδιοτήτων του ρευστού είναι απαραίτητος ο υπολογισμός πολλών
    σταθμισμένων αθροισμάτων που εξαρτώνται απο την απόσταση μεταξύ σωματιδίων. Για να
    εξασφαλιστεί η διατήρηση της ορμής, οι αμοιβαίες συνεισφορές σωματιδίων στα αθροίσματα
    αυτά συμμετρικοποιούνται, με αποτέλεσμα η επιρροή αυτή να λαμβάνει την έννοια της
    αλληλεπίδρασης. Συνεπώς, ο υπολογιστικός φόρτος μειώνεται στο μισό εάν κάθε
    αλληλεπίδραση ληφθεί υποψη μόνο μία φορά για κάθε ζεύγος σωματιδίων που βρίσκονται σε
    απόσταση μικρότερη της ακτίνας εξομάλυνσης. Αυτό επιτυγχάνεται ελέγχοντας μόνο τα μισά
    κελιά γύρω από το τρεχον κελί κατά τη σάρωση του πλέγματος για αλληλεπιδρώντα
    σωματίδια, και μάλιστα αυτά που έχουν ελεγχθεί νωρίτερα, προκειμένου να αυξηθεί η
    πιθανότητα να υπάρχουν ήδη στην κρυφή μνήμη.

** Προσομοίωση
   Η προσομοίωση πραγματοποιείται σε σταθερό χρονικό βήμα που καθορίζεται από το κριτήριο
   CFL. Ανά συγκεκριμένο αριθμό βημάτων εξάγεται και ένα στιγμιότυπο (frame), το οποίο
   περιέχει πληροφορίες για τα σωματίδια, το ρευστό και την ακτογραμμή. Οι συγκρούσεις και
   οι περιορισμοί ανάμεσα στα υλικά σώματα επιλύονται από την bullet, ενώ οι επιπλέον
   δυνάμεις που ασκούνται μεταξύ των σωματιδίων του ρευστού υπολογίζονται μέσω κατάλληλα
   ορισμένης συνάρτησης (callback) στον κύριο βρόχο της προσομοίωσης. Συνοπτικά εντός
   αυτής εκτελούνται τα εξής βήματα:
   1. Καταγραφή και αποθήκευση των ώσεων (impulses) του ρευστού προς την ακτογραμμή
   2. Ενημέρωση του πλέγματος αποθήκευσης των σωματιδίων
   3. Καθαρισμός δεδομένων των σωματιδίων που πρόκειται να επανυπολογιστούν
   4. Ανιχνευση αλληλεπιδράσεων με σάρωση όλου του πλέγματος
   5. Υπολογισμός πυκνότητας στις θέσεις των σωματιδίων μέσω προοδευτικής άθροισης των
      αμοιβαίων συνεισφορών των αλληλεπιδρώντων ζευγών
   6. Υπολογισμός πίεσης στις ίδιες θέσεις μέσω της καταστατικής εξίσωσης του ρευστού,
      συναρτήσει της πυκνότητας
   7. Υπολογισμός και εφαρμογή των ώσεων που υπολογίζονται ως το γινόμενο των δυνάμεων
      πίεσης/ιξώδους και του χρονικού βήματος. Οι δυνάμεις είναι αντισυμμετρικές σε κάθε
      ζεύγος αλληλεπίδρασης, και οι μεν πίεσης είναι ανάλογες της διαφοράς πίεσης μεταξύ
      των δύο σημείων, οι δε ιξώδους της διαφοράς ταχυτήτων.

** Ανακατασκευή επιφάνειας
   Για την ανακατασκευή της επιφάνειας του ρευστού υπολογίζεται σε διατεταγμένα σημεία το
   χρωματικό πεδίο (color field), ένα βαθμωτό πεδίο που ισοδυναμεί με την πυκνότητα του
   ρευστού σε κάθε σημείο του χώρου σύμφωνα με τη μέθοδο SPH. Τα κελιά του πλέγματος
   υποδιαιρούνται ισότροπα σε κυβικά υποκελιά, στις γωνίες των οποίων υπολογίζονται οι
   τιμές του χρωματικού πεδίου, από τις οποίες στη συνέχεια εξάγεται η επιφάνεια του
   ρευστού ως ισοεπιφάνεια του πεδίου με τη συνήθη μέθοδο marching cubes.
   
** Εξαγωγή δεδομένων
   Σε κάθε στιγμιότυπο στης προσομοίωσης εξάγονται 3 αρχεία δεδομένων vtk, τα οποία
   αριθμούνται διαδοχικά για τη δημιουργία χρονοσειράς (timeseries):
   - particles: περιέχει τη θέση, πυκνότητα καθώς και τις δυνάμεις πίεσης/ιξώδους για τα
     σωματίδια της προσομοίωσης
   - color_field: περιέχει τα δείγματα του χρωματικού πεδίου που χρησιμοποιούνται για την
     ανακατασκευή της επιφάνειας του ρευστού
   - terrain_impulses: περιέχει τις ώσεις που ασκούνται από το ρευστό στην ακτογραμμή.
